ALTER TABLE info_regular_equipment
    MODIFY COLUMN CRITERIA_MIN DECIMAL(12,6) NULL,
    MODIFY COLUMN CRITERIA_MAX DECIMAL(12,6) NULL;

ALTER TABLE info_function_equipment
    MODIFY COLUMN CRITERIA_MIN DECIMAL(12,6) NULL,
    MODIFY COLUMN CRITERIA_MAX DECIMAL(12,6) NULL;

ALTER TABLE info_dimension_equipment
    MODIFY COLUMN CRITERIA_MIN DECIMAL(12,6) NULL,
    MODIFY COLUMN CRITERIA_MAX DECIMAL(12,6) NULL;

ALTER TABLE db_regular_data
    MODIFY COLUMN `VALUE` DECIMAL(12,6) NULL;

ALTER TABLE db_dimension_data
    MODIFY COLUMN `VALUE` DECIMAL(12,6) NULL;

ALTER TABLE db_dimension_piece_judge
    MODIFY COLUMN DIFFERENCE DECIMAL(12,6) NULL,
    MODIFY COLUMN TOLERANCE DECIMAL(12,6) NULL;
