CREATE TABLE IF NOT EXISTS info_function_check_method
(
    ID            INT NOT NULL AUTO_INCREMENT,
    M_CODE        VARCHAR(100) NOT NULL,
    CHECK_ORDER   SMALLINT NOT NULL,
    CHECK_DETAIL  VARCHAR(255) NOT NULL,
    INUSE         TINYINT NOT NULL DEFAULT 1,
    UPDATETIME    DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_FUNCTION_CHECK_METHOD (M_CODE, CHECK_ORDER)
);

CREATE TABLE IF NOT EXISTS db_function_check_result
(
    REPORT_NO          VARCHAR(20) NOT NULL,
    `COUNT`            SMALLINT NOT NULL,
    SAMPLING_NO        SMALLINT NOT NULL,
    CAVITY_NAME        VARCHAR(20) NULL,
    LOT_NO             VARCHAR(100) NULL,
    FUNCTION_CHECK_ID  INT NULL,
    CHECK_ORDER        SMALLINT NOT NULL,
    CHECK_DETAIL       VARCHAR(255) NOT NULL,
    JUDGE              TINYINT NULL,
    REMARK             VARCHAR(255) NULL,
    EMP_ID             VARCHAR(20) NULL,
    FUNCTION_DATE      DATETIME NULL,
    INUSE              TINYINT NOT NULL DEFAULT 1,
    UPDATETIME         DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (REPORT_NO, `COUNT`, SAMPLING_NO, CHECK_ORDER),
    KEY IX_FUNCTION_CHECK_RESULT_ACTIVE (REPORT_NO, SAMPLING_NO, INUSE),
    KEY IX_FUNCTION_CHECK_RESULT_METHOD (FUNCTION_CHECK_ID)
);
